---
apiVersion: v1
kind: Secret
metadata:
  name: ipv6-spoke1-master1
  namespace: mgmt-spoke1
data:
  username: YWRtaW4=
  password: YWRyb2dhbGxvcA==
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: ipv6-spoke1-master1
  namespace: mgmt-spoke1
  labels:
    infraenvs.agent-install.openshift.io: "mgmt-spoke1"
  annotations:
    ## Disable the Introspection
    inspect.metal3.io: disabled
    ## Set Static Hostname
    bmac.agent-install.openshift.io/hostname: "ipv6-spoke1-master1"
    ## Set Static Role
    bmac.agent-install.openshift.io/role: "master"
spec:
  online: true
  bootMACAddress: A0:36:9F:6C:0C:11
  automatedCleaningMode: disabled
  bmc:
    address: idrac-virtualmedia+https://[2620:52:0:1300::35]/redfish/v1/Systems/System.Embedded.1
    credentialsName: ipv6-spoke1-master1
    disableCertificateVerification: true
  rootDeviceHints:
    deviceName: "/dev/sda"
